name: appokemon
description: Pokemon App.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  cached_network_image: ^3.2.3
  lottie: ^2.1.0
  flutter_native_splash: ^2.2.16
  shared_preferences: ^2.0.15
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/pokeicon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/img/splash.png
  branding: assets/img/JERODEV-LOGO.png
  branding_mode: bottom

flutter:
  uses-material-design: true

  
  assets:
    - assets/img/
  #   - images/a_dot_ham.jpeg

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 